name: 'SEMVER-regexp-validator'
description: 'Validate SEMVER version with official regex from semver.org'
inputs:
  version:
    description: 'Version to validate'
    required: true
    default: '0.0.0'
outputs:
  is-valid:
    description: 'Return if the input version is valid'
runs:
  using: node20
  main: 'index.js'
branding:
  icon: 'check-square'
  color: 'gray-dark'
